<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "qc_info_rights"
 *
 * Auto generated by Extension Builder 2021-09-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Qc Info Rights',
    'description' => 'Gives editors a view of BE users and group rights like the Access module but in read-only. Also provides BE users and BE User Groups list with CSV export.',
    'category' => 'module',
    'author' => 'Quebec.ca',
    'author_email' => '',
    'state' => 'beta',
    'version' => '2.0.4',
    'autoload' => [
        'psr-4' => [
            'Qc\QcInfoRights\\' => 'Classes',
        ],
    ],
    'constraints' => [
        'depends' => [
            'php' => '8.1-8.3',
            'typo3' => '12.0.0-12.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
