services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Qc\QcInfoRights\:
    resource: '../Classes/*'

  Qc\QcInfoRights\Domain\Repository\BackendUserRepository:
    public: true

  Qc\QcInfoRights\Controller\BaseBackendController:
    tags: [ 'backend.controller' ]

  Qc\QcInfoRights\Controller\GroupsController:
    tags: [ 'backend.controller' ]

  Qc\QcInfoRights\Controller\AccessRightsInfoController:
    tags: [ 'backend.controller' ]

  Qc\QcInfoRights\Controller\UsersInfoController:
    tags: [ 'backend.controller' ]
