services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Qc\QcInfoRights\:
    resource: '../Classes/*'
  Qc\QcInfoRights\Domain\Repository\BackendUserRepository:
    public: true
